In [ ]:
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
from tensorflow.keras.models import Sequential
dataset = loadtxt("/content/pima-indians-diabetes.data.csv",delimiter=',')
dataset





array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [ ]:
X  = dataset[:,0:8]
Y  = dataset[:,8]

X


array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

In [ ]:
model=Sequential()


In [ ]:
model.add(Dense(12,input_dim=8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


In [ ]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])
model.fit(X,Y,epochs=150,batch_size=10)

Epoch 1/150
77/77 [==============================] - 1s 4ms/step - loss: 1.0246 - accuracy: 0.5378
Epoch 2/150
77/77 [==============================] - 0s 3ms/step - loss: 0.7884 - accuracy: 0.6120
Epoch 3/150
77/77 [==============================] - 0s 4ms/step - loss: 0.7214 - accuracy: 0.6276
Epoch 4/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6956 - accuracy: 0.6289
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6923 - accuracy: 0.6250
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6908 - accuracy: 0.6289
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6683 - accuracy: 0.6250
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6651 - accuracy: 0.6419
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6550 - accuracy: 0.6393
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6521 - accuracy: 0.6497
Epoch 11/

In [ ]:
accuracy=model.evaluate(X,Y)
print('accuracy of model is',(accuracy*100))

24/24 [==============================] - 0s 2ms/step - loss: 0.4829 - accuracy: 0.7591
accuracy of model is [0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.4829274117946625, 0.7591145634651184, 0.482927411

In [ ]:
#Using model for prediction class:
prediction = model.predict(X)
exec("for i in range(5):print(X[i].tolist(),prediction[i],Y[i])")

24/24 [==============================] - 0s 2ms/step
[6.0, 148.0, 72.0, 35.0, 0.0, 33.6, 0.627, 50.0] [0.6804206] 1.0
[1.0, 85.0, 66.0, 29.0, 0.0, 26.6, 0.351, 31.0] [0.13239515] 0.0
[8.0, 183.0, 64.0, 0.0, 0.0, 23.3, 0.672, 32.0] [0.8843469] 1.0
[1.0, 89.0, 66.0, 23.0, 94.0, 28.1, 0.167, 21.0] [0.11436945] 0.0
[0.0, 137.0, 40.0, 35.0, 168.0, 43.1, 2.288, 33.0] [0.75824296] 1.0
